name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  backend-tests:
    name: Backend • Jest + Coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
          cache-dependency-path: |
            backend/yarn.lock

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run tests with coverage
        run: yarn test:cov

      - name: Upload HTML Coverage (artifact)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: backend-coverage-html
          path: backend/coverage
          retention-days: 14
